/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laborrow;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author A455L
 */
public class alat extends javax.swing.JFrame {

    /**
     * Creates new form alat
     */
    public alat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        kelas = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        no = new javax.swing.JTextField();
        tanggal = new javax.swing.JTextField();
        kembali = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        deskripsi = new javax.swing.JTextArea();
        alat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("THE CURIOUS INCIDENT", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 102));
        jLabel5.setText("SPLITTER");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(240, 310, 50, 20);

        jLabel6.setFont(new java.awt.Font("THE CURIOUS INCIDENT", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 102));
        jLabel6.setText("SPLICER");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(290, 340, 50, 20);

        jLabel7.setFont(new java.awt.Font("THE CURIOUS INCIDENT", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 102));
        jLabel7.setText("STRIPPER");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(340, 310, 60, 20);

        jLabel8.setFont(new java.awt.Font("THE CURIOUS INCIDENT", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 102));
        jLabel8.setText("KABEL FO");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(400, 340, 60, 20);

        jButton6.setFont(new java.awt.Font("THE CURIOUS INCIDENT", 0, 14)); // NOI18N
        jButton6.setText("LIHAT ALAT");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(450, 270, 90, 30);

        jButton1.setFont(new java.awt.Font("THE CURIOUS INCIDENT", 0, 14)); // NOI18N
        jButton1.setText("SAVE");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(580, 350, 90, 30);

        jButton5.setFont(new java.awt.Font("THE CURIOUS INCIDENT", 0, 14)); // NOI18N
        jButton5.setText("REFRESH");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(680, 310, 90, 30);

        jButton3.setFont(new java.awt.Font("THE CURIOUS INCIDENT", 0, 14)); // NOI18N
        jButton3.setText("CLEAR");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(780, 310, 90, 30);

        jButton2.setFont(new java.awt.Font("THE CURIOUS INCIDENT", 0, 14)); // NOI18N
        jButton2.setText("DELETE");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(680, 350, 90, 30);

        jButton4.setFont(new java.awt.Font("THE CURIOUS INCIDENT", 0, 14)); // NOI18N
        jButton4.setText("PRINT");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(780, 350, 90, 30);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama", "Kelas", "Alat dipinjam", "Tanggal Pinjam", "Tanggal Kembali", "Deskripsi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);
        if (tabel.getColumnModel().getColumnCount() > 0) {
            tabel.getColumnModel().getColumn(0).setResizable(false);
            tabel.getColumnModel().getColumn(1).setResizable(false);
            tabel.getColumnModel().getColumn(2).setResizable(false);
            tabel.getColumnModel().getColumn(3).setResizable(false);
            tabel.getColumnModel().getColumn(4).setResizable(false);
            tabel.getColumnModel().getColumn(5).setResizable(false);
            tabel.getColumnModel().getColumn(6).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 390, 840, 160);

        jLabel4.setFont(new java.awt.Font("Hobo Std", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("No");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(340, 20, 30, 30);

        kelas.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        kelas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kelas.setBorder(null);
        kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelasActionPerformed(evt);
            }
        });
        getContentPane().add(kelas);
        kelas.setBounds(240, 210, 200, 30);

        nama.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        nama.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nama.setBorder(null);
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        getContentPane().add(nama);
        nama.setBounds(240, 150, 200, 30);

        no.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        no.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        no.setBorder(null);
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });
        getContentPane().add(no);
        no.setBounds(370, 20, 60, 30);

        tanggal.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        tanggal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tanggal.setText("xx/xx/xx");
        tanggal.setBorder(null);
        tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalActionPerformed(evt);
            }
        });
        getContentPane().add(tanggal);
        tanggal.setBounds(650, 40, 200, 30);

        kembali.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        kembali.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kembali.setText("xx/xx/xx");
        kembali.setBorder(null);
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali);
        kembali.setBounds(650, 150, 200, 30);

        deskripsi.setColumns(20);
        deskripsi.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        deskripsi.setRows(5);
        deskripsi.setText("Peminjaman untuk ");
        deskripsi.setBorder(null);
        jScrollPane2.setViewportView(deskripsi);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(630, 200, 230, 100);

        alat.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        alat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        alat.setText("KLIK & PILIH ALAT DIBAWAH");
        alat.setBorder(null);
        alat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alatActionPerformed(evt);
            }
        });
        getContentPane().add(alat);
        alat.setBounds(230, 270, 210, 30);

        jLabel3.setFont(new java.awt.Font("THE CURIOUS INCIDENT", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("-- LIHAT DAFTAR ALAT--");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 270, 160, 30);

        jLabel2.setFont(new java.awt.Font("DFPOP1-W9", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("< KEMBALI");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 100, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laborrow/13.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 570);

        setSize(new java.awt.Dimension(916, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        new dua().setVisible(true);
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

          new detil().setVisible(true);
        dispose();



        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void kelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelasActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noActionPerformed

    private void tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembaliActionPerformed

    private void alatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alatActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        int baris = tabel.getSelectedRow();

        if(baris != -1){
            no.setText(tabel.getValueAt(baris, 0).toString());
            nama.setText(tabel.getValueAt(baris, 1).toString());
            kelas.setText(tabel.getValueAt(baris, 2).toString());
            alat.setText(tabel.getValueAt(baris, 3).toString());
            tanggal.setText(tabel.getValueAt(baris, 4).toString());
            kembali.setText(tabel.getValueAt(baris, 5).toString());
            deskripsi.setText(tabel.getValueAt(baris, 6).toString());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if("".equals(no.getText()) || "".equals(nama.getText()) || "".equals(kelas.getText()) || "".equals(alat.getText())|| "".equals(tanggal.getText()) || "".equals(kembali.getText()) || "".equals(deskripsi.getText())){
            JOptionPane.showMessageDialog(this, "HARAP LENGKAPI DATA", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
            String SQL = "INSERT INTO tb_alat " + "VALUES('" + no.getText()+ "','"+nama.getText()+"','"+kelas.getText()+"','"+alat.getText()+"','"+tanggal.getText()+"','"+kembali.getText()+"','"+deskripsi.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if(status == 1){
                JOptionPane.showMessageDialog(this, "DATA BERHASIL DITAMBAHKAN", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();

            }else{
                JOptionPane.showMessageDialog(this, "DATA GAGAL DITAMBAHKAN", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        selectData();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        no.setText("");
        nama.setText("");
        kelas.setText("");
        alat.setText("");
        tanggal.setText("");
        kembali.setText("");
        deskripsi.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int baris = tabel.getSelectedRow();
        if (baris != -1){
            String no = tabel.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_alat WHERE no ='"+no+"'";
            int status = KoneksiDB.execute(SQL);
            if(status == 1){
                JOptionPane.showMessageDialog(this, "DATA BERHASIL DIHAPUS", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else{
                JOptionPane.showMessageDialog(this, "DATA GAGAL DIHAPUS", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "PILIH BARIS DATA DAHULU", "Error", JOptionPane.WARNING_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        MessageFormat header = new MessageFormat("Data Alat yang telah dipinjam");
        MessageFormat footer = new MessageFormat("Page {0, number, integer}     ");
        try {
            tabel.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);

        }catch(java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n", e.getMessage());

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new detil().setVisible(true);
        


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        alat.setText("Splitter");

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked

        alat.setText("Splicer");

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        alat.setText("Stripper");

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
       alat.setText("Kabel FO");

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alat;
    private javax.swing.JTextArea deskripsi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kelas;
    private javax.swing.JTextField kembali;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField no;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField tanggal;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
         String kolom[] = {"no", "nama", "kelas","alat","pinjam","kembali", "deskripsi"};
       DefaultTableModel dtm = new DefaultTableModel(null, kolom);
       String SQL = "SELECT * FROM tb_alat";
       ResultSet rs = KoneksiDB.executeQuery(SQL);
       try{
           while(rs.next()){
               String no = rs.getString(1);
               String nama = rs.getString(2);
               String kelas = rs.getString(3);
               String alat = rs.getString(4);
               String pinjam = rs.getString(5);
               String kembali = rs.getString(6);
               String deskripsi = rs.getString(7);
             
               String data[] = {no,nama, kelas,alat,pinjam, kembali, deskripsi};
               dtm.addRow(data);
               }  
           
           
       }catch (SQLException ex){
           Logger.getLogger(lab.class.getName()).log(Level.SEVERE, null, ex);
           
       }
       tabel.setModel(dtm);
    }
}
